export const CORRECT_ORDER_CARDS = 'CORRECT_ORDER_CARDS';

export const ACTUAL_ORDER_CARDS = 'ACTUAL_ORDER_CARDS';
export const RIGHT_CARD_CLICKED = 'RIGHT_CARD_CLICKED';
export const WRONG_CARD_CLICKED = 'WRONG_CARD_CLICKED';

export const NUM_CORRECT_INCREMENT = 'NUM_CORRECT_INCREMENT';
export const NUM_CORRECT_RESET = 'NUM_CORRECT_RESET';